# Generated by Django 2.1.1 on 2018-09-27 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import est_quote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('est_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mins_piece', models.FloatField()),
                ('mult_dollies', models.FloatField()),
                ('m_cart', models.FloatField()),
                ('l_cart', models.FloatField()),
                ('p_cart', models.FloatField()),
                ('s_pack', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est_quote.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est_quote.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
                ('sub_total', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(default=est_quote.models.make_token, editable=False, max_length=36)),
                ('travel_time', models.IntegerField()),
                ('org_street_load', models.BooleanField()),
                ('org_midrise_elev_std', models.BooleanField()),
                ('org_midrise_elv_frt', models.BooleanField()),
                ('org_highrise', models.BooleanField()),
                ('org_stairs', models.BooleanField()),
                ('org_lng_psh', models.BooleanField()),
                ('dest_street_load', models.BooleanField()),
                ('dest_midrise_elev_std', models.BooleanField()),
                ('dest_midrise_elv_frt', models.BooleanField()),
                ('dest_highrise', models.BooleanField()),
                ('dest_stairs', models.BooleanField()),
                ('dest_lng_psh', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='est_client.Client')),
                ('products', models.ManyToManyField(blank=True, related_name='quote', through='est_quote.ProductProperties', to='est_quote.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteModifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='photo_files/%Y-%m-%d')),
                ('street_load', models.FloatField()),
                ('midrise_elev_std', models.FloatField()),
                ('midrise_elv_frt', models.FloatField()),
                ('highrise', models.FloatField()),
                ('stairs', models.FloatField()),
                ('lng_psh', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='productproperties',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est_quote.Quote'),
        ),
    ]
